app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from app import views

# django admin header customization
admin.site.site_header = "login in Dhaage-Dore"
admin.site.site_title = " Welcome to admin panel "
admin.site.index_title = " Welcome to this portal "

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('products/', views.products, name='products'),
    path('singleproduct/<slug:slug>', views.singleproduct, name='singleproduct'),
    path('contact/', views.contact, name='contact'),
    path('cart/', views.cart, name='cart'),
    path('checkout/<int:cartid>', views.checkout, name='checkout'),
    path('ordertracking/', views.ordertracking, name='ordertracking'),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dhaagedore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models
from django_resized import ResizedImageField
# Create your models here.
from django.utils.text import slugify


class Contact(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    query = models.CharField(max_length=30)
    desc = models.TextField()

    def __str__(self):
        return self.name + " - " + self.query


class Products(models.Model):
    product_img = models.ImageField(upload_to="blogimages/", blank=False)
    product_title = models.CharField(max_length=30, unique=True)
    product_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    product_desc = models.TextField()
    product_count = models.CharField(max_length=10)
    product_slug = models.SlugField(blank=True, null=True, unique=True)
    time = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.product_slug = slugify(self.product_title)
        super(Products, self).save(*args, **kwargs)

    def __str__(self):
        return self.product_title


class ProductImage(models.Model):
    product = models.ForeignKey(Products, verbose_name='Product Title', default=None, on_delete=models.CASCADE)
    product_images = models.ImageField(verbose_name='Image', upload_to='blogimages/')

    class Meta:
        verbose_name_plural = 'Product Images'

    def __str__(self):
        return self.product.product_title


class OrderProductInfo(models.Model):
    order_id = models.IntegerField(blank=True, null=True)
    product = models.ForeignKey(Products, models.SET_NULL, blank=True, null=True)
    product_quantity = models.IntegerField()
    single_product_price = models.DecimalField(max_digits=10, decimal_places=2)
    total_product_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.product.product_title


class CustomePaymentMethod(models.Model):
    made_on = models.DateTimeField(auto_now_add=True)
    upi_transaction_id = models.CharField(max_length=100)
    upi_id = models.CharField(max_length=200)
    payment_proof = models.FileField(upload_to="paymentproof/")

    def __str__(self):
        return str(self.id)


class CourierDetail(models.Model):
    start_delivery_date = models.DateTimeField()
    end_delivery_date = models.DateTimeField()
    company_name = models.CharField(max_length=100)
    contact_no = models.BigIntegerField()
    contact_email = models.EmailField()
    tracking_id = models.CharField(max_length=200)



class Orders(models.Model):
    order_date = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    contry_choice = (('1', 'India'), ('2', 'USA'), ('3', 'Canada'), ('4', 'Bhutan'), ('5', 'Japan'))
    oderpayment_choice = (('1', 'Paytm'), ('2', 'Razorpay'), ('3', 'Custome'))
    orderstatus_choice = (('1', 'Placed'), ('2', 'Confirm'), ('3', 'Out for Delivery'), ('4', 'Complete'), ('5', 'Failed'))
    orderpaymentstatus_choice = (('1', 'Paid'), ('2', 'Pending'), ('3', 'Failed'))
    customer_name = models.CharField(max_length=200)
    customer_address = models.TextField()
    customer_contry = models.CharField(max_length=30, choices=contry_choice)
    customer_state = models.CharField(max_length=100)
    customer_city = models.CharField(max_length=100)
    city_zip = models.IntegerField()
    customer_email = models.EmailField()
    customer_mobile_number = models.BigIntegerField()
    products = models.ManyToManyField(OrderProductInfo)
    order_status = models.CharField(max_length=100, choices=orderstatus_choice)
    order_payment_type = models.CharField(max_length=100, choices=oderpayment_choice)
    order_payment_status = models.CharField(max_length=100, choices=orderpaymentstatus_choice)
    total_order_price = models.DecimalField(max_digits=10, decimal_places=2,blank=True,null=True)
    custom_payment_ref = models.OneToOneField(CustomePaymentMethod, models.SET_NULL, blank=True, null=True)
    courier_detail_ref = models.OneToOneField(CourierDetail, models.SET_NULL, blank=True, null=True)


    def __str__(self):
        return str(self.id)


class CartProductInfo(models.Model):
    product = models.ForeignKey(Products, models.SET_NULL, blank=True, null=True)
    product_quantity = models.IntegerField()
    single_product_price = models.DecimalField(max_digits=10, decimal_places=2)
    total_product_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.product.product_title


class Cart(models.Model):
    products_cart = models.ManyToManyField(CartProductInfo)
    cart_total = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

templates/about.html
{% extends "base.html" %}
{% block title %}about page{% endblock title %}
{% block aboutactive %}active{% endblock aboutactive %}%}
{% block aboutcurrent %}(current){% endblock aboutcurrent %}
{% load static %}
{% block body %}
{% load static %}
<!-- Page Content -->
<!-- About Page Starts Here -->
<div class="about-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-heading mt-0">
                    <div class="line-dec"></div>
                    <h1>About Us</h1>
                </div>
            </div>
            <div class="col-md-6">
                <div class="left-image">
                    <img src="/static/img/about-us.jpg" alt="">
                </div>
            </div>
            <div class="col-md-6">
                <div class="right-content">
                    <h4>Phasellus vel interdum elit</h4>
                    <p> Macrame is a crafting technique that uses knots to create various textiles. Since
                        this art form has regained popularity in recent years, crafters and artists are coming up with
                        innovative ways to take macrame beyond the basic plant hangers and wall hangings.
                        This age-old practice has gone in and out of popularity for thousands of years. However, this
                        method will always be around to some degree because of its practicality. Remarkably, you can
                        make items like table runners and key chains using just your hands and a couple of inexpensive
                        supplies.
                        If you want to learn more about how macrame came to be and how you can get started with a
                        macrame project, keep reading. </p>
                    <br>
                    <p>This age-old practice has gone in and out of popularity for thousands of years. However, this
                        method will always be around to some degree because of its practicality. Remarkably, you can
                        make items like table runners and key chains using just your hands and a couple of inexpensive
                        supplies.</p>
                    <br>
                    <p>Macrame is a technique or method of crafting a textile that uses several knots to form the basic
                        shape and function of the piece. Each knot can be created with your hands, and there are no
                        other tools required other than a mounting ring to keep the item in place while you work.</p>
                    <br>
                    <p>
                        Thank you.</p>
                    <div class="share">
                        <h6>Find us on: <span><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i
                                class="fa fa-instagram"></i></a><a href="#"><i class="fa fa-twitter"></i></a></span>
                        </h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About Page Ends Here -->

{% endblock body %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}home page{% endblock title %}
{% block homeactive %}active{% endblock homeactive %}%}
{% block homecurrent %}(current){% endblock homecurrent %}
{% block body %}

<div class="mt-5">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                    aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                    aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3"
                    aria-label="Slide 4"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'img/home1.jpg' %}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="https://source.unsplash.com/1800x650/?code,html" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="https://source.unsplash.com/1800x650/?computer,nature" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="https://source.unsplash.com/1800x650/?Animal,nature" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

<!-- Featured Starts Here -->
<div class="featured-items">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Featured Items</h1>
            </div>
          </div>
          <div class="col-md-12">
            <div class="owl-carousel owl-theme">
                {% for items in products %}
              <a href="{% url 'singleproduct' items.product_slug %}">
                <div class="featured-item">
                  <img src="{{items.product_img.url}}" alt="Item 1" style="height:300px;width:200;">
                  <h4>{{items.product_title }}</h4>
                  <h6>Price: ₹{{items.product_price }}.00  </h6>
                </div>
              </a>
                {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
<!-- Featred Ends Here -->
{% endblock body %}

templates/mycart.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<style>
body {
    background-color: #eeeeee;
    font-family: 'Open Sans', serif;
    font-size: 14px

}

.container-fluid {
    margin-top: 70px
}

.card-body {
    -ms-flex: 1 1 auto;
    flex: 1 1 auto;
    padding: 1.40rem
}

.img-sm {
    width: 80px;
    height: 80px
}

.itemside .info {
    padding-left: 15px;
    padding-right: 7px
}

.table-shopping-cart .price-wrap {
    line-height: 1.2
}

.table-shopping-cart .price {
    font-weight: bold;
    margin-right: 5px;
    display: block
}

.text-muted {
    color: #969696 !important
}

a {
    text-decoration: none !important
}

.card {
    position: relative;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-direction: column;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 1px solid rgba(0, 0, 0, .125);
    border-radius: 0px
}

.itemside {
    position: relative;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    width: 100%
}

.dlist-align {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex
}

[class*="dlist-"] {
    margin-bottom: 5px
}

.coupon {
    border-radius: 1px
}

.price {
    font-weight: 600;
    color: #212529
}

.btn.btn-out {
    outline: 1px solid #fff;
    outline-offset: -5px
}

.btn-main {
    border-radius: 2px;
    text-transform: capitalize;
    font-size: 15px;
    padding: 10px 19px;
    cursor: pointer;
    color: #fff;
    width: 100%
}

.btn-light {
    color: #ffffff;
    background-color: #F44336;
    border-color: #f8f9fa;
    font-size: 12px
}

.btn-light:hover {
    color: #ffffff;
    background-color: #F44336;
    border-color: #F44336
}

.btn-apply {
    font-size: 11px
}

// plus minus
.quantity {
 display: inline-block; }

.quantity .input-text.qty {
 width: 35px;
 height: 39px;
 padding: 0 5px;
 text-align: center;
 background-color: transparent;
 border: 1px solid #efefef;
}

.quantity.buttons_added {
 text-align: left;
 position: relative;
 white-space: nowrap;
 vertical-align: top; }

.quantity.buttons_added input {
 display: inline-block;
 margin: 0;
 vertical-align: top;
 box-shadow: none;
}

.quantity.buttons_added .minus,
.quantity.buttons_added .plus {
 padding: 7px 10px 8px;
 height: 41px;
 background-color: #ffffff;
 border: 1px solid #efefef;
 cursor:pointer;}

.quantity.buttons_added .minus {
 border-right: 0; }

.quantity.buttons_added .plus {
 border-left: 0; }

.quantity.buttons_added .minus:hover,
.quantity.buttons_added .plus:hover {
 background: #eeeeee; }

.quantity input::-webkit-outer-spin-button,
.quantity input::-webkit-inner-spin-button {
 -webkit-appearance: none;
 -moz-appearance: none;
 margin: 0; }

 .quantity.buttons_added .minus:focus,
.quantity.buttons_added .plus:focus {
 outline: none; }













</style>
{% endblock css %}

{% block title %}MyCart page{% endblock title %}
{% block cartactive %}active{% endblock cartactive %}
{% block cartcurrent %}(current){% endblock cartcurrent %}

{% block body %}

<!-- Page Content -->
<!-- mycart Page Starts Here -->
<div class="container-fluid px-5">
    <div class="row">
        <div class="col-md-4 col-sm-12">
            <div class="section-heading mt-0">
                <div class="line-dec"></div>
                <h1>Cart</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <aside class="col-md-8 pb-5">
            <div class="card">
                <div class="table-responsive">
                    <table class="table table-borderless table-shopping-cart" id="items">
                        <thead class="text-muted">
                        <tr class="small text-uppercase">
                            <th scope="col">Product</th>
                            <th scope="col" width="120">Quantity</th>
                            <th scope="col" width="140">Price</th>
                            <th scope="col" class="text-right d-none d-md-block" width="100"></th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </aside>
        <aside class="col-md-4 ">
            <div class="card mb-3">
                <div class="card-body">
                    <form>
                        <div class="form-group"><label>Have coupon?</label>
                            <div class="input-group"><input type="text" class="form-control coupon" name=""
                                                            placeholder="Coupon code"> <span class="input-group-append"> <button
                                    class="btn btn-primary btn-apply coupon">Apply</button> </span></div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <div id="itemli"></div>
                    <hr>
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="product_cart" id="id_products_cart">
                        <button type="submit" class="btn btn-out btn-primary btn-square btn-main" data-abc="true"> Make
                            Purchase
                        </button>
                    </form>
                    <a href="{% url 'products' %}" class="btn btn-out btn-success btn-square btn-main mt-2"
                       data-abc="true">Continue
                        Shopping</a>
                </div>
            </div>
        </aside>
    </div>
</div>

<!-- mycart Page Ends Here -->

{% endblock body %}

{% block jsblock %}
<script>
     if (localStorage.getItem('cart') == null) {
        var cart = {};
    } else {
        cart = JSON.parse(localStorage.getItem('cart'));
    }
    console.log(cart);
    var sum = 0;
    var total2 = 0;
    if ($.isEmptyObject(cart)) {
        // If object is empty
        mystr = "<p>Your cart is empty, please add some items before checking out ! </p>"
        $('#items').append(mystr);
    }


    for (item in cart) {

        let name = cart[item][1];
        let qty = cart[item][0];
        let singleprice = cart[item][2];
        let imgsrc = cart[item][4];
        let new_slug = cart[item][5];
        sum = sum + qty;
        total = cart[item][3];
        total2 = total2 + total;
        console.log(new_slug.toString());


        mystr = `
        <tr id="trspam${item}">
                            <td>
                                <figure class="itemside align-items-center">
                                    <div class="aside"><img src="${imgsrc}" class="img-sm" id="img${item}"></div>
                                    <figcaption class="info"><a href="${new_slug}" class="title text-dark" data-abc="true">${name}</a>
                                        <p class="text-muted small">In Stock<br> Brand: MAXTRA</p>
                                    </figcaption>
                                </figure>
                            </td>
                            <td>
                                <div class="quantity">
                                    <div class="quantity buttons_added">
                                        <input onclick='minusbtn(this.id , ${item})' type="button" value="-"
                                               class="minus" id="btnminus${item}" >
                                        <span  class="input-text qty text" name="quantity" id="qty${item}" class="plus" >${qty}</span>
                                        <input type="button" value="+" class="plus" id="btnplus${item}"
                                               onclick='plusbtn(this.id, ${item} )'>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="price">
                                <span id="singletotal${item}"  class="price">₹ ${total}.00</span>
                                <small class="text-muted"> ₹ ${singleprice} each </small></div>
                            </td>
                            <td class="text-right d-none d-md-block">
                                 <div class="rem">
                             <a href="" id="clsbtn${item}" onclick="deleteitem(this.id)" class="btn btn-light" data-abc="true">
                                Remove</a>


                        </div></td>

                        </tr>`


        mystrli = `
        <dl class="dlist-align">
                        <dt>${name}:</dt>
                        <dd class="text-right ml-3">₹ <span id= "singletotall${item}">${total}</span>.00</dd>
                    </dl>
        `;
        $('#itemli').append(mystrli);
        $('#items').append(mystr);
    }

    mystrtotal = `
            <dl class="dlist-align">
                        <dt>Total:</dt>
                        <dd class="text-right text-dark b ml-3"><strong>₹ <span id="carttotal">0</span>.00</strong></dd>
                    </dl>`;

    $('#itemli').append(mystrtotal);


     document.getElementById('carttotal').innerText = total2;

function minusbtn(clicked_id){
    var totalf = 0;
    var a = clicked_id.slice(8, );
     cart = JSON.parse(localStorage.getItem('cart'));
        cart[a][0] = cart[a][0] - 1;

        cart[a][0] = Math.max(1, cart[a][0]);
        updateCart(cart);
        $('#id_products_cart').val(JSON.stringify(cart));
        document.getElementById("qty"+a).innerHTML = cart[a][0].toString();
        document.getElementById("singletotal"+a).innerHTML = cart[a][3].toString();
        document.getElementById("singletotall"+a).innerHTML = cart[a][3].toString();
        cart2 = JSON.parse(localStorage.getItem('cart'));
        for(itemm in cart2){
        totalf = totalf + cart[itemm][3];
        }
        document.getElementById('carttotal').innerHTML = totalf;

}


function plusbtn(clicked_id){
    var totalf=0;
    var a = clicked_id.slice(7, );
    cart = JSON.parse(localStorage.getItem('cart'));
    cart[a][0] = cart[a][0] + 1;
    updateCart(cart);
    $('#id_products_cart').val(JSON.stringify(cart));
    document.getElementById("qty"+a).innerHTML = cart[a][0].toString();
    document.getElementById("singletotal"+a).innerHTML = cart[a][3].toString();
    document.getElementById("singletotall"+a).innerHTML = cart[a][3].toString();
    for(itemm in cart){
        totalf = totalf + cart[itemm][3];
        }
    document.getElementById('carttotal').innerHTML = totalf;
}


    $('#id_products_cart').val(JSON.stringify(cart));








</script>
{% endblock jsblock %}

templates/ordertrackingdetails.html
{% if orderstatus %}
<article class="card">
    <div class="card-body">
        <div>
            <dl class="row text-uppercase">
                <dt class="col-sm-2">Order ID</dt>
                <dd class="col-sm-9">: 00000{{ order_obj.id }}</dd>
                <dt class="col-sm-2">Name</dt>
                <dd class="col-sm-9">: {{ order_obj.customer_name }}</dd>
                <dt class="col-sm-2">Address</dt>
                <dd class="col-sm-9">: {{ order_obj.customer_address }}, {{ order_obj.customer_city }}, {{ order_obj.customer_state }}, {{ order_obj.get_customer_contry_display }}</dd>
                <dt class="col-sm-2 text-truncate">Email</dt>
                <dd class="col-sm-9">: {{ order_obj.customer_email }}</dd>
                <dt class="col-sm-2 text-truncate">Phone no</dt>
                <dd class="col-sm-9">: {{ order_obj.customer_mobile_number }}</dd>
                <dt class="col-sm-2 text-truncate">Order date</dt>
                <dd class="col-sm-9">: {{ order_obj.order_date }}</dd>
            </dl>
        </div>
        {% if order_obj.courier_detail_ref %}
        <article class="card">
            <header class="card-header">Courier Details</header>
            <div class="card-body row">
                <div class="col"><strong>Estimated Delivery time:</strong> <br>
                {{ order_obj.courier_detail_ref.end_delivery_date }}</div>
                <div class="col"><strong>Shipping BY:</strong> <br>{{ order_obj.courier_detail_ref.company_name }} 
                </div>
                <div class="col"><strong>Contact:</strong> <br> <i class="fa fa-phone"></i>
                    +{{ order_obj.courier_detail_ref.contact_no }}<br><i class="fa fa-envelope"></i>
                    {{ order_obj.courier_detail_ref.contact_email }}</div>
                <div class="col"><strong>Tracking #:</strong> <br> {{ order_obj.courier_detail_ref.tracking_id }}</div>
            </div>
        </article>
        {% endif %}
        <div class="track">
            {% if order_obj.order_status == '1' or order_obj.order_status == '2' or order_obj.order_status == '3' or order_obj.order_status == '4'%}
            {% if order_obj.order_status == '1' %}
            <div class="step active"><span class="icon"> <i class="fa fa-bell"></i> </span> <span class="text"> Order placed</span>
            </div>
            <div class="step"><span class="icon"> <i class="fa fa-check"></i> </span> <span class="text">Order confirmed</span>
            </div>
            <div class="step"><span class="icon"> <i class="fa fa-truck"></i> </span> <span class="text"> Out for Delivery </span>
            </div>
            <div class="step"><span class="icon"> <i class="fa fa-cube"></i> </span> <span class="text">Order Complete</span>
            </div>
            {% elif order_obj.order_status == '2' %}
            <div class="step active"><span class="icon"> <i class="fa fa-bell"></i> </span> <span class="text"> Order placed</span>
            </div>
            <div class="step active"><span class="icon"> <i class="fa fa-check"></i> </span> <span class="text">Order confirmed</span>
            </div>
            <div class="step"><span class="icon"> <i class="fa fa-truck"></i> </span> <span class="text"> Out for Delivery </span>
            </div>
            <div class="step"><span class="icon"> <i class="fa fa-cube"></i> </span> <span class="text">Order Complete</span>
            </div>
            {% elif order_obj.order_status == '3' %}
            <div class="step active"><span class="icon"> <i class="fa fa-bell"></i> </span> <span class="text"> Order placed</span>
            </div>
            <div class="step active"><span class="icon"> <i class="fa fa-check"></i> </span> <span class="text">Order confirmed</span>
            </div>
            <div class="step active"><span class="icon"> <i class="fa fa-truck"></i> </span> <span class="text"> Out for Delivery </span>
            </div>
            <div class="step"><span class="icon"> <i class="fa fa-cube"></i> </span> <span class="text">Order Complete</span>
            </div>
            {% elif order_obj.order_status == '4' %}
            <div class="step active"><span class="icon"> <i class="fa fa-bell"></i> </span> <span class="text"> Order placed</span>
            </div>
            <div class="step active"><span class="icon"> <i class="fa fa-check"></i> </span> <span class="text">Order confirmed</span>
            </div>
            <div class="step active"><span class="icon"> <i class="fa fa-truck"></i> </span> <span class="text"> Out for Delivery </span>
            </div>
            <div class="step active"><span class="icon"> <i class="fa fa-cube"></i> </span> <span class="text">Order Complete</span>
            </div>
            {% endif%}
            {% else %}
            <div class="step active"><span class="icon"> <i class="fa fa-exclamation-triangle"></i> </span> <span class="text">Order has failed</span>
            </div>
            {% endif %}
        </div>
        <hr>
        <div class="row">
            <div class="col-md-12 order-md-2 mb-4">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Order Products</span>
                </h4>
                <div class="card">
                    <div class="table-responsive">
                        <table class="table table-borderless table-shopping-cart" id="items">
                            <thead class="text-muted">
                                <tr class="small text-uppercase">
                                    <th scope="col">Product</th>
                                    <th scope="col" width="60">#</th>
                                    <th scope="col" width="120">Price</th>
                                </tr>
                                {% for product in order_obj.products.all %}
                                <tr>
                                    <td>
                                        <figure class="itemside align-items-center">
                                            <div class="aside"><img src="{{ product.product.product_img.url }}" class="img-sm" id=""></div>
                                            <figcaption class="info">
                                                <h6 class="title text-dark" data-abc="true">
                                                    {{product.product.product_title}}</h6>
                                            </figcaption>
                                        </figure>
                                    </td>
                                    <td>
                                        <div class="quantity">
                                            <div class="quantity buttons_added">
                                                <span class="text" name="quantity"><b>{{ product.product_quantity }}</b></span>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="price-wrap"><span class="price">₹{{ product.total_product_price }}</span>
                                            <small class="text-muted"> ₹{{ product.single_product_price }} each </small></div>
                                    </td>
                                </tr>
                                {% endfor %}
                                <tr class="text-success">
                                    <td><span>Total (Rupee)</span></td>
                                    <td></td>
                                    <td><strong> ₹{{ order_obj.total_order_price }}</strong></td>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <a href="{% url 'products' %}" class="btn btn-warning" data-abc="true"> <i class="fa fa-chevron-left"></i> Back to Shoping</a>
    </div>
</article>
{% else %}
<div class="alert alert-warning alert-dismissible fade show">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Warning!</strong> Something Went to Wrong, Please check Order id And Email id.
</div>
</div>
{% endif %}